service: url-shortener

custom:
  stage: ${opt:stage, local}

plugins:
  - serverless-bundle
  - serverless-dotenv-plugin
  - serverless-iam-roles-per-function

package:
  individually: true

provider:
  name: aws
  region: us-east-1
  profile: jlowrya-admin
  environment:
   STAGE: ${self:custom.stage}
   tableName: !Ref urlTable

functions:
  create:
    handler: api/create.main
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:PutItem
        Resource: !GetAtt urlTable.Arn
    events:
      - http:
          path: urls
          method: post
          cors: true
  get:
    handler: api/get.main
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:GetItem
        Resource: !GetAtt urlTable.Arn
    events:
      - http:
          path: urls/{id}
          method: get
          cors: true
  update:
    handler: api/update.main
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:UpdateItem
        Resource: !GetAtt urlTable.Arn
    events:
      - http:
          path: urls/{id}
          method: put
          cors: true
  redirect:
    handler: api/redirect.main
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:GetItem
        Resource: !GetAtt urlTable.Arn
    events:
      - http:
          path: /{id}
          method: get
          cors: true

resources:
  Resources:
    urlTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.stage}-urls
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1